name: SecDim

on: pull_request

jobs:
  secdim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SecDim sha256sum check (exact match)
        run: |
          echo $(curl https://secdim.com/assets/images/logo.svg) | sha256sum

